### ISSUE TITLE
Refaktor

### ISSUE THREAD

**Issue by xenteros** [Wint1993/Knights-tour#1]
Cześć, chcesz zostać programistą Java. Znajdź trochę czasu na usunięcie tych ceplusplusowych podkreślników. Daj tutaj znać jak go skończysz, to wskażę Ci konkretne miejsca, które warto zrefaktorować.

**Comment by Wint1993** [comment]
Siemka

    Zmieniłem to o co prosiłeś ;) czekam na dalsze wskazówki

W dniu 17 lipca 2017 15:33 użytkownik xenteros <notifications@github.com>
napisał:

**Comment by Wint1993** [comment]
Teraz powinno być ok ;)

**Comment by xenteros** [comment]
Do gitgnore dodaj:
- [x] /out
- [x] .idea
- [x] .iml
Nazwy:
- [x] Chess1
- [x] tab1
- [x] camelCase

**Comment by Wint1993** [comment]
Ale ja w tym projekcie nie mam gitignore ;d muszę go mieć ?

**Comment by xenteros** [comment]
to wywal jeszcze te śmieci z repo :) gitgnore powinien być w każdym projekcie, w którym używasz gita
